DROP TYPE IF EXISTS field_type_enum CASCADE;
DROP TYPE IF EXISTS cell_state_enum CASCADE;

DROP TABLE IF EXISTS Gen CASCADE;
DROP TABLE IF EXISTS SequencedBank CASCADE;
DROP TABLE IF EXISTS Achievements CASCADE;
DROP TABLE IF EXISTS Settings CASCADE;
DROP TABLE IF EXISTS Save CASCADE;
DROP TABLE IF EXISTS Simulation CASCADE;
DROP TABLE IF EXISTS Users CASCADE;
DROP TABLE IF EXISTS Genome CASCADE;
DROP TABLE IF EXISTS SequencedGenome CASCADE;
DROP TABLE IF EXISTS Cell CASCADE;
DROP TABLE IF EXISTS CellSettings CASCADE;
DROP TABLE IF EXISTS GenInGenome CASCADE;
DROP TABLE IF EXISTS Statistics CASCADE;
DROP TABLE IF EXISTS GenomeStatistics CASCADE;

-- Possible index deleting
-- DROP INDEX IF EXISTS idx_genome_gen_id;
-- DROP INDEX IF EXISTS idx_save_name;
-- DROP INDEX IF EXISTS idx_statistics_simulation_id;
-- DROP INDEX IF EXISTS idx_cell_settings_id;
-- DROP INDEX IF EXISTS idx_save_create_time;